import type { Metadata } from "next";
import { getProfile } from "@/lib/api";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/Header";
import { Profile } from "../lib/types";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const damion = localFont({
  src: "./fonts/Damion-Regular.ttf",
  variable: "--font-damion",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch profile directly within the component
  const profile: Profile[] = await getProfile();
  console.log("profile", profile);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${damion.variable} antialiased`}
      >
        <Header profileData={profile} />
        {children}
      </body>
    </html>
  );
}
